version: '3.7'

services:
  webapp:
    container_name: 'webapi'
    image: webapi
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ${ConnectionString}

  postgres:
    container_name: postgres
    image: postgres   
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PostgresUser}
      - POSTGRES_PASSWORD=${PostgresPassword}
      - POSTGRES_DB=${PostgresDbName}
    volumes:
      - stackup_postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.17
    env_file:
      - .env
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PgAdminEmail}
      PGADMIN_DEFAULT_PASSWORD: ${PgAdminPassword}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8009:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  stackup_postgres_data:
  pgadmin-data: