version: '3.7'

services:
  webapp:
    container_name: 'webapi'
    image: webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=host=postgres;Port=5432;Database=CrealutionDb;User Id=Validay;Password=Kepnar7878;"

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=Validay
      - POSTGRES_PASSWORD=Kepnar7878
      - POSTGRES_DB=CrealutionDb
    volumes:
      - stackup_postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.17
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: validaypromabe@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Kepnar7878
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8009:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  stackup_postgres_data:
  pgadmin-data: