// <auto-generated />
using CrealutionServer.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrealutionServer.Infrastructure.Migrations
{
    [DbContext(typeof(CrealutionDb))]
    [Migration("20231122205058_InitializeMigration")]
    partial class InitializeMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrealutionServer.Domain.Entities.CreatureStatisticType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("StatisticTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StatisticTypeId");

                    b.ToTable("CreatureStatisticTypes");
                });

            modelBuilder.Entity("CrealutionServer.Domain.Entities.StatisticType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("StatisticTypes");
                });

            modelBuilder.Entity("CrealutionServer.Domain.Entities.CreatureStatisticType", b =>
                {
                    b.HasOne("CrealutionServer.Domain.Entities.StatisticType", "StatisticType")
                        .WithMany("CreatureStatisticTypes")
                        .HasForeignKey("StatisticTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatisticType");
                });

            modelBuilder.Entity("CrealutionServer.Domain.Entities.StatisticType", b =>
                {
                    b.Navigation("CreatureStatisticTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
